# FIN-R1 金融推理模型配置

# 模型路径配置
model_path: "C:/Users/Sycamore/Fin-R1"  # FIN-R1模型本地路径

# 模型推理配置
device: "cuda"  # 使用GPU加速，如果没有GPU则改为 "cpu"
batch_size: 1   # 批处理大小
max_length: 2048  # 最大输入长度
temperature: 0.7  # 生成温度，控制输出的随机性
top_p: 0.9       # nucleus sampling参数
do_sample: true  # 是否使用采样

# 模型能力配置
enable_reasoning: true  # 启用推理能力
enable_planning: true   # 启用规划能力
enable_reflection: true # 启用反思能力

# 金融领域配置
financial_domains:
  - "股票分析"
  - "风险评估"
  - "投资建议"
  - "市场趋势"
  - "资产配置"

# 响应格式
response_format:
  include_reasoning: true   # 包含推理过程
  include_confidence: true  # 包含置信度
  include_alternatives: true # 包含备选方案
  max_suggestions: 3        # 最多建议数量

# 安全配置
safety:
  max_position_size: 0.3    # 单一持仓不超过30%
  risk_warning_threshold: 0.15  # 风险警告阈值
  require_diversification: true # 要求分散投资

