# FIN-R1模型配置文件
model:
  # 模型路径（相对于FinLoom-server目录）
  model_path: ".Fin-R1"
  
  # 设备配置
  device: "cpu"  # 可选: "cpu", "cuda", "mps"
  
  # 推理参数
  max_length: 2048
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  do_sample: true
  num_beams: 1
  repetition_penalty: 1.1
  
  # 批处理配置
  batch_size: 1
  max_batch_size: 8
  
  # 缓存配置
  use_cache: true
  cache_dir: "cache/fin_r1"

# 提示词模板
prompts:
  investment_analysis: |
    你是FinLoom智能投资系统的AI助手。请分析以下投资需求：
    
    用户输入：{user_input}
    
    已解析信息：
    - 投资金额：{investment_amount}
    - 风险偏好：{risk_tolerance}
    - 投资期限：{investment_horizon}
    - 投资目标：{investment_goals}
    - 约束条件：{constraints}
    
    请提供：
    1. 策略建议（conservative/balanced/growth/aggressive）
    2. 风险评估（low/moderate/high/very_high）
    3. 市场展望（bullish/neutral/bearish）
    4. 推荐行业板块（列表）
    5. 需要规避的板块（列表）
    6. 置信度评分（0-1）
    
    以JSON格式返回结果。

  strategy_generation: |
    基于以下投资需求生成具体投资策略：
    
    风险偏好：{risk_tolerance}
    投资期限：{investment_horizon}
    投资目标：{goals}
    市场环境：{market_conditions}
    
    请生成包含以下内容的策略：
    1. 策略组合配置
    2. 仓位管理方法
    3. 再平衡频率
    4. 风险控制措施

  risk_assessment: |
    请评估以下投资方案的风险：
    
    投资策略：{strategy}
    市场环境：{market_conditions}
    用户风险偏好：{risk_tolerance}
    
    请提供：
    1. 最大回撤预期
    2. 波动率预期
    3. 风险等级
    4. 风险控制建议

# 输出解析配置
output_parsing:
  # JSON提取
  extract_json: true
  
  # 字段映射
  field_mapping:
    strategy_recommendation: ["策略建议", "strategy", "recommendation"]
    risk_assessment: ["风险评估", "risk", "risk_level"]
    confidence_score: ["置信度", "confidence", "score"]
    market_outlook: ["市场展望", "outlook", "market_view"]
    sector_preferences: ["推荐板块", "sectors", "preferred_sectors"]
    excluded_sectors: ["规避板块", "excluded", "avoid_sectors"]

# 性能配置
performance:
  # 超时设置（秒）
  timeout: 30
  
  # 重试配置
  max_retries: 3
  retry_delay: 1
  
  # 并发控制
  max_concurrent_requests: 5

# 日志配置
logging:
  log_requests: true
  log_responses: true
  log_level: "INFO"
