# 交易配置文件

# 交易账户配置
account:
  initial_capital: 1000000
  currency: "CNY"
  broker: "simulation"

# 交易规则配置
trading_rules:
  allow_short: false
  max_position_size: 0.1  # 单个标的最大持仓比例
  min_trade_amount: 100   # 最小交易金额
  slippage_bps: 5         # 滑点（基点）
  commission_rate: 0.001  # 佣金费率

# 风险管理配置
risk_management:
  max_drawdown: 0.2       # 最大回撤
  position_limit: 0.1     # 单个标的仓位限制
  sector_limit: 0.3       # 行业集中度限制
  stop_loss: 0.05         # 止损比例

# 执行配置
execution:
  order_type: "limit"     # 默认订单类型
  time_in_force: "day"    # 有效期
  urgency: "normal"       # 紧急程度
  max_participation: 0.1  # 最大市场参与度

# 回测配置
backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  commission_rate: 0.001
  slippage_model: "fixed"
  market_impact: "linear"