# 时间常量
TRADING_DAYS_PER_YEAR = 252
MINUTES_PER_TRADING_DAY = 390
DEFAULT_TIMEZONE = "Asia/Shanghai"

# 数据常量
MAX_SYMBOLS_PER_REQUEST = 100
DEFAULT_LOOKBACK_DAYS = 365
DATA_QUALITY_THRESHOLD = 0.95

# 模型常量
DEFAULT_BATCH_SIZE = 32
MAX_EPOCHS = 100
EARLY_STOPPING_PATIENCE = 10

# 交易常量
MIN_POSITION_SIZE = 100
MAX_POSITION_PCT = 0.1
DEFAULT_SLIPPAGE_BPS = 5

# 系统常量
LOG_LEVEL = "INFO"
MAX_RETRY_ATTEMPTS = 3
TIMEOUT_SECONDS = 30
